// Code generated by mockery. DO NOT EDIT.

package config

import (
	big "math/big"

	config "github.com/cosmos/eureka-relayer/shared/config"
	mock "github.com/stretchr/testify/mock"
)

// MockConfigReader is an autogenerated mock type for the ConfigReader type
type MockConfigReader struct {
	mock.Mock
}

type MockConfigReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigReader) EXPECT() *MockConfigReader_Expecter {
	return &MockConfigReader_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with no fields
func (_m *MockConfigReader) Config() config.Config {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Config
	if rf, ok := ret.Get(0).(func() config.Config); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.Config)
	}

	return r0
}

// MockConfigReader_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockConfigReader_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) Config() *MockConfigReader_Config_Call {
	return &MockConfigReader_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockConfigReader_Config_Call) Run(run func()) *MockConfigReader_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_Config_Call) Return(_a0 config.Config) *MockConfigReader_Config_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigReader_Config_Call) RunAndReturn(run func() config.Config) *MockConfigReader_Config_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllChainConfigsOfType provides a mock function with given fields: chainType
func (_m *MockConfigReader) GetAllChainConfigsOfType(chainType config.ChainType) ([]config.ChainConfig, error) {
	ret := _m.Called(chainType)

	if len(ret) == 0 {
		panic("no return value specified for GetAllChainConfigsOfType")
	}

	var r0 []config.ChainConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(config.ChainType) ([]config.ChainConfig, error)); ok {
		return rf(chainType)
	}
	if rf, ok := ret.Get(0).(func(config.ChainType) []config.ChainConfig); ok {
		r0 = rf(chainType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.ChainConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(config.ChainType) error); ok {
		r1 = rf(chainType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigReader_GetAllChainConfigsOfType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllChainConfigsOfType'
type MockConfigReader_GetAllChainConfigsOfType_Call struct {
	*mock.Call
}

// GetAllChainConfigsOfType is a helper method to define mock.On call
//   - chainType config.ChainType
func (_e *MockConfigReader_Expecter) GetAllChainConfigsOfType(chainType interface{}) *MockConfigReader_GetAllChainConfigsOfType_Call {
	return &MockConfigReader_GetAllChainConfigsOfType_Call{Call: _e.mock.On("GetAllChainConfigsOfType", chainType)}
}

func (_c *MockConfigReader_GetAllChainConfigsOfType_Call) Run(run func(chainType config.ChainType)) *MockConfigReader_GetAllChainConfigsOfType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(config.ChainType))
	})
	return _c
}

func (_c *MockConfigReader_GetAllChainConfigsOfType_Call) Return(_a0 []config.ChainConfig, _a1 error) *MockConfigReader_GetAllChainConfigsOfType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigReader_GetAllChainConfigsOfType_Call) RunAndReturn(run func(config.ChainType) ([]config.ChainConfig, error)) *MockConfigReader_GetAllChainConfigsOfType_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllChains provides a mock function with no fields
func (_m *MockConfigReader) GetAllChains() []config.ChainConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllChains")
	}

	var r0 []config.ChainConfig
	if rf, ok := ret.Get(0).(func() []config.ChainConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.ChainConfig)
		}
	}

	return r0
}

// MockConfigReader_GetAllChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllChains'
type MockConfigReader_GetAllChains_Call struct {
	*mock.Call
}

// GetAllChains is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) GetAllChains() *MockConfigReader_GetAllChains_Call {
	return &MockConfigReader_GetAllChains_Call{Call: _e.mock.On("GetAllChains")}
}

func (_c *MockConfigReader_GetAllChains_Call) Run(run func()) *MockConfigReader_GetAllChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_GetAllChains_Call) Return(_a0 []config.ChainConfig) *MockConfigReader_GetAllChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigReader_GetAllChains_Call) RunAndReturn(run func() []config.ChainConfig) *MockConfigReader_GetAllChains_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllEurekaClientsToCounterparties provides a mock function with no fields
func (_m *MockConfigReader) GetAllEurekaClientsToCounterparties() (map[string]map[string]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllEurekaClientsToCounterparties")
	}

	var r0 map[string]map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func() (map[string]map[string]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() map[string]map[string]string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigReader_GetAllEurekaClientsToCounterparties_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllEurekaClientsToCounterparties'
type MockConfigReader_GetAllEurekaClientsToCounterparties_Call struct {
	*mock.Call
}

// GetAllEurekaClientsToCounterparties is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) GetAllEurekaClientsToCounterparties() *MockConfigReader_GetAllEurekaClientsToCounterparties_Call {
	return &MockConfigReader_GetAllEurekaClientsToCounterparties_Call{Call: _e.mock.On("GetAllEurekaClientsToCounterparties")}
}

func (_c *MockConfigReader_GetAllEurekaClientsToCounterparties_Call) Run(run func()) *MockConfigReader_GetAllEurekaClientsToCounterparties_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_GetAllEurekaClientsToCounterparties_Call) Return(_a0 map[string]map[string]string, _a1 error) *MockConfigReader_GetAllEurekaClientsToCounterparties_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigReader_GetAllEurekaClientsToCounterparties_Call) RunAndReturn(run func() (map[string]map[string]string, error)) *MockConfigReader_GetAllEurekaClientsToCounterparties_Call {
	_c.Call.Return(run)
	return _c
}

// GetBasicAuth provides a mock function with given fields: chainID
func (_m *MockConfigReader) GetBasicAuth(chainID string) (*string, error) {
	ret := _m.Called(chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetBasicAuth")
	}

	var r0 *string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*string, error)); ok {
		return rf(chainID)
	}
	if rf, ok := ret.Get(0).(func(string) *string); ok {
		r0 = rf(chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigReader_GetBasicAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBasicAuth'
type MockConfigReader_GetBasicAuth_Call struct {
	*mock.Call
}

// GetBasicAuth is a helper method to define mock.On call
//   - chainID string
func (_e *MockConfigReader_Expecter) GetBasicAuth(chainID interface{}) *MockConfigReader_GetBasicAuth_Call {
	return &MockConfigReader_GetBasicAuth_Call{Call: _e.mock.On("GetBasicAuth", chainID)}
}

func (_c *MockConfigReader_GetBasicAuth_Call) Run(run func(chainID string)) *MockConfigReader_GetBasicAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigReader_GetBasicAuth_Call) Return(_a0 *string, _a1 error) *MockConfigReader_GetBasicAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigReader_GetBasicAuth_Call) RunAndReturn(run func(string) (*string, error)) *MockConfigReader_GetBasicAuth_Call {
	_c.Call.Return(run)
	return _c
}

// GetChainConfig provides a mock function with given fields: chainID
func (_m *MockConfigReader) GetChainConfig(chainID string) (config.ChainConfig, error) {
	ret := _m.Called(chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetChainConfig")
	}

	var r0 config.ChainConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (config.ChainConfig, error)); ok {
		return rf(chainID)
	}
	if rf, ok := ret.Get(0).(func(string) config.ChainConfig); ok {
		r0 = rf(chainID)
	} else {
		r0 = ret.Get(0).(config.ChainConfig)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigReader_GetChainConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChainConfig'
type MockConfigReader_GetChainConfig_Call struct {
	*mock.Call
}

// GetChainConfig is a helper method to define mock.On call
//   - chainID string
func (_e *MockConfigReader_Expecter) GetChainConfig(chainID interface{}) *MockConfigReader_GetChainConfig_Call {
	return &MockConfigReader_GetChainConfig_Call{Call: _e.mock.On("GetChainConfig", chainID)}
}

func (_c *MockConfigReader_GetChainConfig_Call) Run(run func(chainID string)) *MockConfigReader_GetChainConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigReader_GetChainConfig_Call) Return(_a0 config.ChainConfig, _a1 error) *MockConfigReader_GetChainConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigReader_GetChainConfig_Call) RunAndReturn(run func(string) (config.ChainConfig, error)) *MockConfigReader_GetChainConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetChainEnvironment provides a mock function with given fields: chainID
func (_m *MockConfigReader) GetChainEnvironment(chainID string) (config.ChainEnvironment, error) {
	ret := _m.Called(chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetChainEnvironment")
	}

	var r0 config.ChainEnvironment
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (config.ChainEnvironment, error)); ok {
		return rf(chainID)
	}
	if rf, ok := ret.Get(0).(func(string) config.ChainEnvironment); ok {
		r0 = rf(chainID)
	} else {
		r0 = ret.Get(0).(config.ChainEnvironment)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigReader_GetChainEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChainEnvironment'
type MockConfigReader_GetChainEnvironment_Call struct {
	*mock.Call
}

// GetChainEnvironment is a helper method to define mock.On call
//   - chainID string
func (_e *MockConfigReader_Expecter) GetChainEnvironment(chainID interface{}) *MockConfigReader_GetChainEnvironment_Call {
	return &MockConfigReader_GetChainEnvironment_Call{Call: _e.mock.On("GetChainEnvironment", chainID)}
}

func (_c *MockConfigReader_GetChainEnvironment_Call) Run(run func(chainID string)) *MockConfigReader_GetChainEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigReader_GetChainEnvironment_Call) Return(_a0 config.ChainEnvironment, _a1 error) *MockConfigReader_GetChainEnvironment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigReader_GetChainEnvironment_Call) RunAndReturn(run func(string) (config.ChainEnvironment, error)) *MockConfigReader_GetChainEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientCounterpartyChainID provides a mock function with given fields: chainID, clientID
func (_m *MockConfigReader) GetClientCounterpartyChainID(chainID string, clientID string) (string, error) {
	ret := _m.Called(chainID, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetClientCounterpartyChainID")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (string, error)); ok {
		return rf(chainID, clientID)
	}
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(chainID, clientID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(chainID, clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigReader_GetClientCounterpartyChainID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientCounterpartyChainID'
type MockConfigReader_GetClientCounterpartyChainID_Call struct {
	*mock.Call
}

// GetClientCounterpartyChainID is a helper method to define mock.On call
//   - chainID string
//   - clientID string
func (_e *MockConfigReader_Expecter) GetClientCounterpartyChainID(chainID interface{}, clientID interface{}) *MockConfigReader_GetClientCounterpartyChainID_Call {
	return &MockConfigReader_GetClientCounterpartyChainID_Call{Call: _e.mock.On("GetClientCounterpartyChainID", chainID, clientID)}
}

func (_c *MockConfigReader_GetClientCounterpartyChainID_Call) Run(run func(chainID string, clientID string)) *MockConfigReader_GetClientCounterpartyChainID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockConfigReader_GetClientCounterpartyChainID_Call) Return(_a0 string, _a1 error) *MockConfigReader_GetClientCounterpartyChainID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigReader_GetClientCounterpartyChainID_Call) RunAndReturn(run func(string, string) (string, error)) *MockConfigReader_GetClientCounterpartyChainID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCoingeckoConfig provides a mock function with no fields
func (_m *MockConfigReader) GetCoingeckoConfig() config.CoingeckoConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCoingeckoConfig")
	}

	var r0 config.CoingeckoConfig
	if rf, ok := ret.Get(0).(func() config.CoingeckoConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.CoingeckoConfig)
	}

	return r0
}

// MockConfigReader_GetCoingeckoConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCoingeckoConfig'
type MockConfigReader_GetCoingeckoConfig_Call struct {
	*mock.Call
}

// GetCoingeckoConfig is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) GetCoingeckoConfig() *MockConfigReader_GetCoingeckoConfig_Call {
	return &MockConfigReader_GetCoingeckoConfig_Call{Call: _e.mock.On("GetCoingeckoConfig")}
}

func (_c *MockConfigReader_GetCoingeckoConfig_Call) Run(run func()) *MockConfigReader_GetCoingeckoConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_GetCoingeckoConfig_Call) Return(_a0 config.CoingeckoConfig) *MockConfigReader_GetCoingeckoConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigReader_GetCoingeckoConfig_Call) RunAndReturn(run func() config.CoingeckoConfig) *MockConfigReader_GetCoingeckoConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetEurekaChains provides a mock function with no fields
func (_m *MockConfigReader) GetEurekaChains() []config.ChainConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEurekaChains")
	}

	var r0 []config.ChainConfig
	if rf, ok := ret.Get(0).(func() []config.ChainConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.ChainConfig)
		}
	}

	return r0
}

// MockConfigReader_GetEurekaChains_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEurekaChains'
type MockConfigReader_GetEurekaChains_Call struct {
	*mock.Call
}

// GetEurekaChains is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) GetEurekaChains() *MockConfigReader_GetEurekaChains_Call {
	return &MockConfigReader_GetEurekaChains_Call{Call: _e.mock.On("GetEurekaChains")}
}

func (_c *MockConfigReader_GetEurekaChains_Call) Run(run func()) *MockConfigReader_GetEurekaChains_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_GetEurekaChains_Call) Return(_a0 []config.ChainConfig) *MockConfigReader_GetEurekaChains_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigReader_GetEurekaChains_Call) RunAndReturn(run func() []config.ChainConfig) *MockConfigReader_GetEurekaChains_Call {
	_c.Call.Return(run)
	return _c
}

// GetEurekaConfig provides a mock function with given fields: chainID
func (_m *MockConfigReader) GetEurekaConfig(chainID string) (*config.EurekaConfig, error) {
	ret := _m.Called(chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetEurekaConfig")
	}

	var r0 *config.EurekaConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*config.EurekaConfig, error)); ok {
		return rf(chainID)
	}
	if rf, ok := ret.Get(0).(func(string) *config.EurekaConfig); ok {
		r0 = rf(chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.EurekaConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigReader_GetEurekaConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEurekaConfig'
type MockConfigReader_GetEurekaConfig_Call struct {
	*mock.Call
}

// GetEurekaConfig is a helper method to define mock.On call
//   - chainID string
func (_e *MockConfigReader_Expecter) GetEurekaConfig(chainID interface{}) *MockConfigReader_GetEurekaConfig_Call {
	return &MockConfigReader_GetEurekaConfig_Call{Call: _e.mock.On("GetEurekaConfig", chainID)}
}

func (_c *MockConfigReader_GetEurekaConfig_Call) Run(run func(chainID string)) *MockConfigReader_GetEurekaConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigReader_GetEurekaConfig_Call) Return(_a0 *config.EurekaConfig, _a1 error) *MockConfigReader_GetEurekaConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigReader_GetEurekaConfig_Call) RunAndReturn(run func(string) (*config.EurekaConfig, error)) *MockConfigReader_GetEurekaConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetEurekaProofRelayerConfig provides a mock function with no fields
func (_m *MockConfigReader) GetEurekaProofRelayerConfig() config.EurekaProofAPIConfig {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetEurekaProofRelayerConfig")
	}

	var r0 config.EurekaProofAPIConfig
	if rf, ok := ret.Get(0).(func() config.EurekaProofAPIConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(config.EurekaProofAPIConfig)
	}

	return r0
}

// MockConfigReader_GetEurekaProofRelayerConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEurekaProofRelayerConfig'
type MockConfigReader_GetEurekaProofRelayerConfig_Call struct {
	*mock.Call
}

// GetEurekaProofRelayerConfig is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) GetEurekaProofRelayerConfig() *MockConfigReader_GetEurekaProofRelayerConfig_Call {
	return &MockConfigReader_GetEurekaProofRelayerConfig_Call{Call: _e.mock.On("GetEurekaProofRelayerConfig")}
}

func (_c *MockConfigReader_GetEurekaProofRelayerConfig_Call) Run(run func()) *MockConfigReader_GetEurekaProofRelayerConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_GetEurekaProofRelayerConfig_Call) Return(_a0 config.EurekaProofAPIConfig) *MockConfigReader_GetEurekaProofRelayerConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigReader_GetEurekaProofRelayerConfig_Call) RunAndReturn(run func() config.EurekaProofAPIConfig) *MockConfigReader_GetEurekaProofRelayerConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetGRPCEndpoint provides a mock function with given fields: chainID
func (_m *MockConfigReader) GetGRPCEndpoint(chainID string) (string, bool, error) {
	ret := _m.Called(chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetGRPCEndpoint")
	}

	var r0 string
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(string) (string, bool, error)); ok {
		return rf(chainID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(chainID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) bool); ok {
		r1 = rf(chainID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(string) error); ok {
		r2 = rf(chainID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockConfigReader_GetGRPCEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGRPCEndpoint'
type MockConfigReader_GetGRPCEndpoint_Call struct {
	*mock.Call
}

// GetGRPCEndpoint is a helper method to define mock.On call
//   - chainID string
func (_e *MockConfigReader_Expecter) GetGRPCEndpoint(chainID interface{}) *MockConfigReader_GetGRPCEndpoint_Call {
	return &MockConfigReader_GetGRPCEndpoint_Call{Call: _e.mock.On("GetGRPCEndpoint", chainID)}
}

func (_c *MockConfigReader_GetGRPCEndpoint_Call) Run(run func(chainID string)) *MockConfigReader_GetGRPCEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigReader_GetGRPCEndpoint_Call) Return(_a0 string, _a1 bool, _a2 error) *MockConfigReader_GetGRPCEndpoint_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockConfigReader_GetGRPCEndpoint_Call) RunAndReturn(run func(string) (string, bool, error)) *MockConfigReader_GetGRPCEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetPostgresConnString provides a mock function with no fields
func (_m *MockConfigReader) GetPostgresConnString() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPostgresConnString")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockConfigReader_GetPostgresConnString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPostgresConnString'
type MockConfigReader_GetPostgresConnString_Call struct {
	*mock.Call
}

// GetPostgresConnString is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) GetPostgresConnString() *MockConfigReader_GetPostgresConnString_Call {
	return &MockConfigReader_GetPostgresConnString_Call{Call: _e.mock.On("GetPostgresConnString")}
}

func (_c *MockConfigReader_GetPostgresConnString_Call) Run(run func()) *MockConfigReader_GetPostgresConnString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_GetPostgresConnString_Call) Return(_a0 string) *MockConfigReader_GetPostgresConnString_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigReader_GetPostgresConnString_Call) RunAndReturn(run func() string) *MockConfigReader_GetPostgresConnString_Call {
	_c.Call.Return(run)
	return _c
}

// GetRPCEndpoint provides a mock function with given fields: chainID
func (_m *MockConfigReader) GetRPCEndpoint(chainID string) (string, error) {
	ret := _m.Called(chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetRPCEndpoint")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(chainID)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(chainID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigReader_GetRPCEndpoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRPCEndpoint'
type MockConfigReader_GetRPCEndpoint_Call struct {
	*mock.Call
}

// GetRPCEndpoint is a helper method to define mock.On call
//   - chainID string
func (_e *MockConfigReader_Expecter) GetRPCEndpoint(chainID interface{}) *MockConfigReader_GetRPCEndpoint_Call {
	return &MockConfigReader_GetRPCEndpoint_Call{Call: _e.mock.On("GetRPCEndpoint", chainID)}
}

func (_c *MockConfigReader_GetRPCEndpoint_Call) Run(run func(chainID string)) *MockConfigReader_GetRPCEndpoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockConfigReader_GetRPCEndpoint_Call) Return(_a0 string, _a1 error) *MockConfigReader_GetRPCEndpoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigReader_GetRPCEndpoint_Call) RunAndReturn(run func(string) (string, error)) *MockConfigReader_GetRPCEndpoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetSignerGasAlertThresholds provides a mock function with given fields: chainID, bridgeType
func (_m *MockConfigReader) GetSignerGasAlertThresholds(chainID string, bridgeType config.BridgeType) (*big.Int, *big.Int, error) {
	ret := _m.Called(chainID, bridgeType)

	if len(ret) == 0 {
		panic("no return value specified for GetSignerGasAlertThresholds")
	}

	var r0 *big.Int
	var r1 *big.Int
	var r2 error
	if rf, ok := ret.Get(0).(func(string, config.BridgeType) (*big.Int, *big.Int, error)); ok {
		return rf(chainID, bridgeType)
	}
	if rf, ok := ret.Get(0).(func(string, config.BridgeType) *big.Int); ok {
		r0 = rf(chainID, bridgeType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(string, config.BridgeType) *big.Int); ok {
		r1 = rf(chainID, bridgeType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*big.Int)
		}
	}

	if rf, ok := ret.Get(2).(func(string, config.BridgeType) error); ok {
		r2 = rf(chainID, bridgeType)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockConfigReader_GetSignerGasAlertThresholds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSignerGasAlertThresholds'
type MockConfigReader_GetSignerGasAlertThresholds_Call struct {
	*mock.Call
}

// GetSignerGasAlertThresholds is a helper method to define mock.On call
//   - chainID string
//   - bridgeType config.BridgeType
func (_e *MockConfigReader_Expecter) GetSignerGasAlertThresholds(chainID interface{}, bridgeType interface{}) *MockConfigReader_GetSignerGasAlertThresholds_Call {
	return &MockConfigReader_GetSignerGasAlertThresholds_Call{Call: _e.mock.On("GetSignerGasAlertThresholds", chainID, bridgeType)}
}

func (_c *MockConfigReader_GetSignerGasAlertThresholds_Call) Run(run func(chainID string, bridgeType config.BridgeType)) *MockConfigReader_GetSignerGasAlertThresholds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(config.BridgeType))
	})
	return _c
}

func (_c *MockConfigReader_GetSignerGasAlertThresholds_Call) Return(warningThreshold *big.Int, criticalThreshold *big.Int, err error) *MockConfigReader_GetSignerGasAlertThresholds_Call {
	_c.Call.Return(warningThreshold, criticalThreshold, err)
	return _c
}

func (_c *MockConfigReader_GetSignerGasAlertThresholds_Call) RunAndReturn(run func(string, config.BridgeType) (*big.Int, *big.Int, error)) *MockConfigReader_GetSignerGasAlertThresholds_Call {
	_c.Call.Return(run)
	return _c
}

// PostgresIAMAuthEnabled provides a mock function with no fields
func (_m *MockConfigReader) PostgresIAMAuthEnabled() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PostgresIAMAuthEnabled")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockConfigReader_PostgresIAMAuthEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostgresIAMAuthEnabled'
type MockConfigReader_PostgresIAMAuthEnabled_Call struct {
	*mock.Call
}

// PostgresIAMAuthEnabled is a helper method to define mock.On call
func (_e *MockConfigReader_Expecter) PostgresIAMAuthEnabled() *MockConfigReader_PostgresIAMAuthEnabled_Call {
	return &MockConfigReader_PostgresIAMAuthEnabled_Call{Call: _e.mock.On("PostgresIAMAuthEnabled")}
}

func (_c *MockConfigReader_PostgresIAMAuthEnabled_Call) Run(run func()) *MockConfigReader_PostgresIAMAuthEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockConfigReader_PostgresIAMAuthEnabled_Call) Return(_a0 bool) *MockConfigReader_PostgresIAMAuthEnabled_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigReader_PostgresIAMAuthEnabled_Call) RunAndReturn(run func() bool) *MockConfigReader_PostgresIAMAuthEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigReader creates a new instance of MockConfigReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigReader {
	mock := &MockConfigReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
