// Code generated by mockery. DO NOT EDIT.

package relayerapi

import (
	context "context"
	db "github.com/cosmos/eureka-relayer/db/gen/db"

	mock "github.com/stretchr/testify/mock"
)

// MockRelayerAPIQueries is an autogenerated mock type for the RelayerAPIQueries type
type MockRelayerAPIQueries struct {
	mock.Mock
}

type MockRelayerAPIQueries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRelayerAPIQueries) EXPECT() *MockRelayerAPIQueries_Expecter {
	return &MockRelayerAPIQueries_Expecter{mock: &_m.Mock}
}

// InsertEurekaTransfer provides a mock function with given fields: ctx, arg
func (_m *MockRelayerAPIQueries) InsertEurekaTransfer(ctx context.Context, arg db.InsertEurekaTransferParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertEurekaTransfer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.InsertEurekaTransferParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRelayerAPIQueries_InsertEurekaTransfer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertEurekaTransfer'
type MockRelayerAPIQueries_InsertEurekaTransfer_Call struct {
	*mock.Call
}

// InsertEurekaTransfer is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.InsertEurekaTransferParams
func (_e *MockRelayerAPIQueries_Expecter) InsertEurekaTransfer(ctx interface{}, arg interface{}) *MockRelayerAPIQueries_InsertEurekaTransfer_Call {
	return &MockRelayerAPIQueries_InsertEurekaTransfer_Call{Call: _e.mock.On("InsertEurekaTransfer", ctx, arg)}
}

func (_c *MockRelayerAPIQueries_InsertEurekaTransfer_Call) Run(run func(ctx context.Context, arg db.InsertEurekaTransferParams)) *MockRelayerAPIQueries_InsertEurekaTransfer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.InsertEurekaTransferParams))
	})
	return _c
}

func (_c *MockRelayerAPIQueries_InsertEurekaTransfer_Call) Return(_a0 error) *MockRelayerAPIQueries_InsertEurekaTransfer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRelayerAPIQueries_InsertEurekaTransfer_Call) RunAndReturn(run func(context.Context, db.InsertEurekaTransferParams) error) *MockRelayerAPIQueries_InsertEurekaTransfer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRelayerAPIQueries creates a new instance of MockRelayerAPIQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRelayerAPIQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRelayerAPIQueries {
	mock := &MockRelayerAPIQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
