// Code generated by mockery. DO NOT EDIT.

package eureka

import (
	context "context"
	db "github.com/cosmos/eureka-relayer/db/gen/db"
	eureka "github.com/cosmos/eureka-relayer/relayer/eureka"

	mock "github.com/stretchr/testify/mock"
)

// MockEurekaProcessor is an autogenerated mock type for the EurekaProcessor type
type MockEurekaProcessor struct {
	mock.Mock
}

type MockEurekaProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEurekaProcessor) EXPECT() *MockEurekaProcessor_Expecter {
	return &MockEurekaProcessor_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: i, err
func (_m *MockEurekaProcessor) Cancel(i *eureka.EurekaTransfer, err error) {
	_m.Called(i, err)
}

// MockEurekaProcessor_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockEurekaProcessor_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - i *eureka.EurekaTransfer
//   - err error
func (_e *MockEurekaProcessor_Expecter) Cancel(i interface{}, err interface{}) *MockEurekaProcessor_Cancel_Call {
	return &MockEurekaProcessor_Cancel_Call{Call: _e.mock.On("Cancel", i, err)}
}

func (_c *MockEurekaProcessor_Cancel_Call) Run(run func(i *eureka.EurekaTransfer, err error)) *MockEurekaProcessor_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*eureka.EurekaTransfer), args[1].(error))
	})
	return _c
}

func (_c *MockEurekaProcessor_Cancel_Call) Return() *MockEurekaProcessor_Cancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEurekaProcessor_Cancel_Call) RunAndReturn(run func(*eureka.EurekaTransfer, error)) *MockEurekaProcessor_Cancel_Call {
	_c.Run(run)
	return _c
}

// Process provides a mock function with given fields: ctx, i
func (_m *MockEurekaProcessor) Process(ctx context.Context, i *eureka.EurekaTransfer) (*eureka.EurekaTransfer, error) {
	ret := _m.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *eureka.EurekaTransfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eureka.EurekaTransfer) (*eureka.EurekaTransfer, error)); ok {
		return rf(ctx, i)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eureka.EurekaTransfer) *eureka.EurekaTransfer); ok {
		r0 = rf(ctx, i)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*eureka.EurekaTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eureka.EurekaTransfer) error); ok {
		r1 = rf(ctx, i)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEurekaProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockEurekaProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - i *eureka.EurekaTransfer
func (_e *MockEurekaProcessor_Expecter) Process(ctx interface{}, i interface{}) *MockEurekaProcessor_Process_Call {
	return &MockEurekaProcessor_Process_Call{Call: _e.mock.On("Process", ctx, i)}
}

func (_c *MockEurekaProcessor_Process_Call) Run(run func(ctx context.Context, i *eureka.EurekaTransfer)) *MockEurekaProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*eureka.EurekaTransfer))
	})
	return _c
}

func (_c *MockEurekaProcessor_Process_Call) Return(_a0 *eureka.EurekaTransfer, _a1 error) *MockEurekaProcessor_Process_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEurekaProcessor_Process_Call) RunAndReturn(run func(context.Context, *eureka.EurekaTransfer) (*eureka.EurekaTransfer, error)) *MockEurekaProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldProcess provides a mock function with given fields: input
func (_m *MockEurekaProcessor) ShouldProcess(input *eureka.EurekaTransfer) bool {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ShouldProcess")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*eureka.EurekaTransfer) bool); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEurekaProcessor_ShouldProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldProcess'
type MockEurekaProcessor_ShouldProcess_Call struct {
	*mock.Call
}

// ShouldProcess is a helper method to define mock.On call
//   - input *eureka.EurekaTransfer
func (_e *MockEurekaProcessor_Expecter) ShouldProcess(input interface{}) *MockEurekaProcessor_ShouldProcess_Call {
	return &MockEurekaProcessor_ShouldProcess_Call{Call: _e.mock.On("ShouldProcess", input)}
}

func (_c *MockEurekaProcessor_ShouldProcess_Call) Run(run func(input *eureka.EurekaTransfer)) *MockEurekaProcessor_ShouldProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*eureka.EurekaTransfer))
	})
	return _c
}

func (_c *MockEurekaProcessor_ShouldProcess_Call) Return(_a0 bool) *MockEurekaProcessor_ShouldProcess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEurekaProcessor_ShouldProcess_Call) RunAndReturn(run func(*eureka.EurekaTransfer) bool) *MockEurekaProcessor_ShouldProcess_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with no fields
func (_m *MockEurekaProcessor) State() db.EurekaRelayStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 db.EurekaRelayStatus
	if rf, ok := ret.Get(0).(func() db.EurekaRelayStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(db.EurekaRelayStatus)
	}

	return r0
}

// MockEurekaProcessor_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockEurekaProcessor_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockEurekaProcessor_Expecter) State() *MockEurekaProcessor_State_Call {
	return &MockEurekaProcessor_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockEurekaProcessor_State_Call) Run(run func()) *MockEurekaProcessor_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEurekaProcessor_State_Call) Return(_a0 db.EurekaRelayStatus) *MockEurekaProcessor_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEurekaProcessor_State_Call) RunAndReturn(run func() db.EurekaRelayStatus) *MockEurekaProcessor_State_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEurekaProcessor creates a new instance of MockEurekaProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEurekaProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEurekaProcessor {
	mock := &MockEurekaProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
