// Code generated by mockery. DO NOT EDIT.

package eureka

import (
	context "context"
	db "github.com/cosmos/eureka-relayer/db/gen/db"

	mock "github.com/stretchr/testify/mock"
)

// MockUnfinishedEurekaTransferStorage is an autogenerated mock type for the UnfinishedEurekaTransferStorage type
type MockUnfinishedEurekaTransferStorage struct {
	mock.Mock
}

type MockUnfinishedEurekaTransferStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnfinishedEurekaTransferStorage) EXPECT() *MockUnfinishedEurekaTransferStorage_Expecter {
	return &MockUnfinishedEurekaTransferStorage_Expecter{mock: &_m.Mock}
}

// GetUnfinishedEurekaTransfers provides a mock function with given fields: ctx
func (_m *MockUnfinishedEurekaTransferStorage) GetUnfinishedEurekaTransfers(ctx context.Context) ([]db.EurekaTransfer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnfinishedEurekaTransfers")
	}

	var r0 []db.EurekaTransfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.EurekaTransfer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.EurekaTransfer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.EurekaTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUnfinishedEurekaTransferStorage_GetUnfinishedEurekaTransfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnfinishedEurekaTransfers'
type MockUnfinishedEurekaTransferStorage_GetUnfinishedEurekaTransfers_Call struct {
	*mock.Call
}

// GetUnfinishedEurekaTransfers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnfinishedEurekaTransferStorage_Expecter) GetUnfinishedEurekaTransfers(ctx interface{}) *MockUnfinishedEurekaTransferStorage_GetUnfinishedEurekaTransfers_Call {
	return &MockUnfinishedEurekaTransferStorage_GetUnfinishedEurekaTransfers_Call{Call: _e.mock.On("GetUnfinishedEurekaTransfers", ctx)}
}

func (_c *MockUnfinishedEurekaTransferStorage_GetUnfinishedEurekaTransfers_Call) Run(run func(ctx context.Context)) *MockUnfinishedEurekaTransferStorage_GetUnfinishedEurekaTransfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUnfinishedEurekaTransferStorage_GetUnfinishedEurekaTransfers_Call) Return(_a0 []db.EurekaTransfer, _a1 error) *MockUnfinishedEurekaTransferStorage_GetUnfinishedEurekaTransfers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUnfinishedEurekaTransferStorage_GetUnfinishedEurekaTransfers_Call) RunAndReturn(run func(context.Context) ([]db.EurekaTransfer, error)) *MockUnfinishedEurekaTransferStorage_GetUnfinishedEurekaTransfers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferState provides a mock function with given fields: ctx, arg
func (_m *MockUnfinishedEurekaTransferStorage) UpdateTransferState(ctx context.Context, arg db.UpdateTransferStateParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferStateParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnfinishedEurekaTransferStorage_UpdateTransferState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferState'
type MockUnfinishedEurekaTransferStorage_UpdateTransferState_Call struct {
	*mock.Call
}

// UpdateTransferState is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferStateParams
func (_e *MockUnfinishedEurekaTransferStorage_Expecter) UpdateTransferState(ctx interface{}, arg interface{}) *MockUnfinishedEurekaTransferStorage_UpdateTransferState_Call {
	return &MockUnfinishedEurekaTransferStorage_UpdateTransferState_Call{Call: _e.mock.On("UpdateTransferState", ctx, arg)}
}

func (_c *MockUnfinishedEurekaTransferStorage_UpdateTransferState_Call) Run(run func(ctx context.Context, arg db.UpdateTransferStateParams)) *MockUnfinishedEurekaTransferStorage_UpdateTransferState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferStateParams))
	})
	return _c
}

func (_c *MockUnfinishedEurekaTransferStorage_UpdateTransferState_Call) Return(_a0 error) *MockUnfinishedEurekaTransferStorage_UpdateTransferState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnfinishedEurekaTransferStorage_UpdateTransferState_Call) RunAndReturn(run func(context.Context, db.UpdateTransferStateParams) error) *MockUnfinishedEurekaTransferStorage_UpdateTransferState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnfinishedEurekaTransferStorage creates a new instance of MockUnfinishedEurekaTransferStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnfinishedEurekaTransferStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnfinishedEurekaTransferStorage {
	mock := &MockUnfinishedEurekaTransferStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
