// Code generated by mockery. DO NOT EDIT.

package eureka

import (
	context "context"

	eureka "github.com/cosmos/eureka-relayer/relayer/eureka"
	mock "github.com/stretchr/testify/mock"
)

// MockPipelineManager is an autogenerated mock type for the PipelineManager type
type MockPipelineManager struct {
	mock.Mock
}

type MockPipelineManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPipelineManager) EXPECT() *MockPipelineManager_Expecter {
	return &MockPipelineManager_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockPipelineManager) Close() {
	_m.Called()
}

// MockPipelineManager_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockPipelineManager_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockPipelineManager_Expecter) Close() *MockPipelineManager_Close_Call {
	return &MockPipelineManager_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockPipelineManager_Close_Call) Run(run func()) *MockPipelineManager_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPipelineManager_Close_Call) Return() *MockPipelineManager_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPipelineManager_Close_Call) RunAndReturn(run func()) *MockPipelineManager_Close_Call {
	_c.Run(run)
	return _c
}

// Pipeline provides a mock function with given fields: ctx, transfer
func (_m *MockPipelineManager) Pipeline(ctx context.Context, transfer *eureka.EurekaTransfer) (eureka.EurekaPipeline, error) {
	ret := _m.Called(ctx, transfer)

	if len(ret) == 0 {
		panic("no return value specified for Pipeline")
	}

	var r0 eureka.EurekaPipeline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *eureka.EurekaTransfer) (eureka.EurekaPipeline, error)); ok {
		return rf(ctx, transfer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *eureka.EurekaTransfer) eureka.EurekaPipeline); ok {
		r0 = rf(ctx, transfer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(eureka.EurekaPipeline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *eureka.EurekaTransfer) error); ok {
		r1 = rf(ctx, transfer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPipelineManager_Pipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pipeline'
type MockPipelineManager_Pipeline_Call struct {
	*mock.Call
}

// Pipeline is a helper method to define mock.On call
//   - ctx context.Context
//   - transfer *eureka.EurekaTransfer
func (_e *MockPipelineManager_Expecter) Pipeline(ctx interface{}, transfer interface{}) *MockPipelineManager_Pipeline_Call {
	return &MockPipelineManager_Pipeline_Call{Call: _e.mock.On("Pipeline", ctx, transfer)}
}

func (_c *MockPipelineManager_Pipeline_Call) Run(run func(ctx context.Context, transfer *eureka.EurekaTransfer)) *MockPipelineManager_Pipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*eureka.EurekaTransfer))
	})
	return _c
}

func (_c *MockPipelineManager_Pipeline_Call) Return(_a0 eureka.EurekaPipeline, _a1 error) *MockPipelineManager_Pipeline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPipelineManager_Pipeline_Call) RunAndReturn(run func(context.Context, *eureka.EurekaTransfer) (eureka.EurekaPipeline, error)) *MockPipelineManager_Pipeline_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPipelineManager creates a new instance of MockPipelineManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPipelineManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPipelineManager {
	mock := &MockPipelineManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
