// Code generated by mockery. DO NOT EDIT.

package eureka

import (
	context "context"
	eureka "github.com/cosmos/eureka-relayer/shared/bridges/eureka"

	mock "github.com/stretchr/testify/mock"
)

// MockBridgeClientManager is an autogenerated mock type for the BridgeClientManager type
type MockBridgeClientManager struct {
	mock.Mock
}

type MockBridgeClientManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBridgeClientManager) EXPECT() *MockBridgeClientManager_Expecter {
	return &MockBridgeClientManager_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function with given fields: ctx, chainID
func (_m *MockBridgeClientManager) GetClient(ctx context.Context, chainID string) (eureka.BridgeClient, error) {
	ret := _m.Called(ctx, chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 eureka.BridgeClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (eureka.BridgeClient, error)); ok {
		return rf(ctx, chainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) eureka.BridgeClient); ok {
		r0 = rf(ctx, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(eureka.BridgeClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBridgeClientManager_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockBridgeClientManager_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
func (_e *MockBridgeClientManager_Expecter) GetClient(ctx interface{}, chainID interface{}) *MockBridgeClientManager_GetClient_Call {
	return &MockBridgeClientManager_GetClient_Call{Call: _e.mock.On("GetClient", ctx, chainID)}
}

func (_c *MockBridgeClientManager_GetClient_Call) Run(run func(ctx context.Context, chainID string)) *MockBridgeClientManager_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBridgeClientManager_GetClient_Call) Return(_a0 eureka.BridgeClient, _a1 error) *MockBridgeClientManager_GetClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBridgeClientManager_GetClient_Call) RunAndReturn(run func(context.Context, string) (eureka.BridgeClient, error)) *MockBridgeClientManager_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBridgeClientManager creates a new instance of MockBridgeClientManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBridgeClientManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBridgeClientManager {
	mock := &MockBridgeClientManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
