// Code generated by mockery. DO NOT EDIT.

package eureka

import (
	context "context"
	db "github.com/cosmos/eureka-relayer/db/gen/db"
	eureka "github.com/cosmos/eureka-relayer/relayer/eureka"

	mock "github.com/stretchr/testify/mock"
)

// MockEurekaBatchProcessor is an autogenerated mock type for the EurekaBatchProcessor type
type MockEurekaBatchProcessor struct {
	mock.Mock
}

type MockEurekaBatchProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEurekaBatchProcessor) EXPECT() *MockEurekaBatchProcessor_Expecter {
	return &MockEurekaBatchProcessor_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: i, err
func (_m *MockEurekaBatchProcessor) Cancel(i []*eureka.EurekaTransfer, err error) {
	_m.Called(i, err)
}

// MockEurekaBatchProcessor_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockEurekaBatchProcessor_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - i []*eureka.EurekaTransfer
//   - err error
func (_e *MockEurekaBatchProcessor_Expecter) Cancel(i interface{}, err interface{}) *MockEurekaBatchProcessor_Cancel_Call {
	return &MockEurekaBatchProcessor_Cancel_Call{Call: _e.mock.On("Cancel", i, err)}
}

func (_c *MockEurekaBatchProcessor_Cancel_Call) Run(run func(i []*eureka.EurekaTransfer, err error)) *MockEurekaBatchProcessor_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*eureka.EurekaTransfer), args[1].(error))
	})
	return _c
}

func (_c *MockEurekaBatchProcessor_Cancel_Call) Return() *MockEurekaBatchProcessor_Cancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEurekaBatchProcessor_Cancel_Call) RunAndReturn(run func([]*eureka.EurekaTransfer, error)) *MockEurekaBatchProcessor_Cancel_Call {
	_c.Run(run)
	return _c
}

// Process provides a mock function with given fields: ctx, i
func (_m *MockEurekaBatchProcessor) Process(ctx context.Context, i []*eureka.EurekaTransfer) ([]*eureka.EurekaTransfer, error) {
	ret := _m.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 []*eureka.EurekaTransfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []*eureka.EurekaTransfer) ([]*eureka.EurekaTransfer, error)); ok {
		return rf(ctx, i)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []*eureka.EurekaTransfer) []*eureka.EurekaTransfer); ok {
		r0 = rf(ctx, i)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*eureka.EurekaTransfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []*eureka.EurekaTransfer) error); ok {
		r1 = rf(ctx, i)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEurekaBatchProcessor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockEurekaBatchProcessor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - i []*eureka.EurekaTransfer
func (_e *MockEurekaBatchProcessor_Expecter) Process(ctx interface{}, i interface{}) *MockEurekaBatchProcessor_Process_Call {
	return &MockEurekaBatchProcessor_Process_Call{Call: _e.mock.On("Process", ctx, i)}
}

func (_c *MockEurekaBatchProcessor_Process_Call) Run(run func(ctx context.Context, i []*eureka.EurekaTransfer)) *MockEurekaBatchProcessor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*eureka.EurekaTransfer))
	})
	return _c
}

func (_c *MockEurekaBatchProcessor_Process_Call) Return(_a0 []*eureka.EurekaTransfer, _a1 error) *MockEurekaBatchProcessor_Process_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEurekaBatchProcessor_Process_Call) RunAndReturn(run func(context.Context, []*eureka.EurekaTransfer) ([]*eureka.EurekaTransfer, error)) *MockEurekaBatchProcessor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldProcess provides a mock function with given fields: input
func (_m *MockEurekaBatchProcessor) ShouldProcess(input *eureka.EurekaTransfer) bool {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ShouldProcess")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*eureka.EurekaTransfer) bool); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockEurekaBatchProcessor_ShouldProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldProcess'
type MockEurekaBatchProcessor_ShouldProcess_Call struct {
	*mock.Call
}

// ShouldProcess is a helper method to define mock.On call
//   - input *eureka.EurekaTransfer
func (_e *MockEurekaBatchProcessor_Expecter) ShouldProcess(input interface{}) *MockEurekaBatchProcessor_ShouldProcess_Call {
	return &MockEurekaBatchProcessor_ShouldProcess_Call{Call: _e.mock.On("ShouldProcess", input)}
}

func (_c *MockEurekaBatchProcessor_ShouldProcess_Call) Run(run func(input *eureka.EurekaTransfer)) *MockEurekaBatchProcessor_ShouldProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*eureka.EurekaTransfer))
	})
	return _c
}

func (_c *MockEurekaBatchProcessor_ShouldProcess_Call) Return(_a0 bool) *MockEurekaBatchProcessor_ShouldProcess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEurekaBatchProcessor_ShouldProcess_Call) RunAndReturn(run func(*eureka.EurekaTransfer) bool) *MockEurekaBatchProcessor_ShouldProcess_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with no fields
func (_m *MockEurekaBatchProcessor) State() db.EurekaRelayStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 db.EurekaRelayStatus
	if rf, ok := ret.Get(0).(func() db.EurekaRelayStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(db.EurekaRelayStatus)
	}

	return r0
}

// MockEurekaBatchProcessor_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockEurekaBatchProcessor_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockEurekaBatchProcessor_Expecter) State() *MockEurekaBatchProcessor_State_Call {
	return &MockEurekaBatchProcessor_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockEurekaBatchProcessor_State_Call) Run(run func()) *MockEurekaBatchProcessor_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEurekaBatchProcessor_State_Call) Return(_a0 db.EurekaRelayStatus) *MockEurekaBatchProcessor_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEurekaBatchProcessor_State_Call) RunAndReturn(run func() db.EurekaRelayStatus) *MockEurekaBatchProcessor_State_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEurekaBatchProcessor creates a new instance of MockEurekaBatchProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEurekaBatchProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEurekaBatchProcessor {
	mock := &MockEurekaBatchProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
