// Code generated by mockery. DO NOT EDIT.

package ibcv2

import (
	context "context"

	db "github.com/cosmos/ibc-relayer/db/gen/db"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// ClearAckTx provides a mock function with given fields: ctx, args
func (_m *MockStorage) ClearAckTx(ctx context.Context, args db.ClearAckTxParams) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ClearAckTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ClearAckTxParams) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_ClearAckTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearAckTx'
type MockStorage_ClearAckTx_Call struct {
	*mock.Call
}

// ClearAckTx is a helper method to define mock.On call
//   - ctx context.Context
//   - args db.ClearAckTxParams
func (_e *MockStorage_Expecter) ClearAckTx(ctx interface{}, args interface{}) *MockStorage_ClearAckTx_Call {
	return &MockStorage_ClearAckTx_Call{Call: _e.mock.On("ClearAckTx", ctx, args)}
}

func (_c *MockStorage_ClearAckTx_Call) Run(run func(ctx context.Context, args db.ClearAckTxParams)) *MockStorage_ClearAckTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ClearAckTxParams))
	})
	return _c
}

func (_c *MockStorage_ClearAckTx_Call) Return(_a0 error) *MockStorage_ClearAckTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_ClearAckTx_Call) RunAndReturn(run func(context.Context, db.ClearAckTxParams) error) *MockStorage_ClearAckTx_Call {
	_c.Call.Return(run)
	return _c
}

// ClearRecvTx provides a mock function with given fields: ctx, args
func (_m *MockStorage) ClearRecvTx(ctx context.Context, args db.ClearRecvTxParams) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ClearRecvTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ClearRecvTxParams) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_ClearRecvTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearRecvTx'
type MockStorage_ClearRecvTx_Call struct {
	*mock.Call
}

// ClearRecvTx is a helper method to define mock.On call
//   - ctx context.Context
//   - args db.ClearRecvTxParams
func (_e *MockStorage_Expecter) ClearRecvTx(ctx interface{}, args interface{}) *MockStorage_ClearRecvTx_Call {
	return &MockStorage_ClearRecvTx_Call{Call: _e.mock.On("ClearRecvTx", ctx, args)}
}

func (_c *MockStorage_ClearRecvTx_Call) Run(run func(ctx context.Context, args db.ClearRecvTxParams)) *MockStorage_ClearRecvTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ClearRecvTxParams))
	})
	return _c
}

func (_c *MockStorage_ClearRecvTx_Call) Return(_a0 error) *MockStorage_ClearRecvTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_ClearRecvTx_Call) RunAndReturn(run func(context.Context, db.ClearRecvTxParams) error) *MockStorage_ClearRecvTx_Call {
	_c.Call.Return(run)
	return _c
}

// ClearTimeoutTx provides a mock function with given fields: ctx, args
func (_m *MockStorage) ClearTimeoutTx(ctx context.Context, args db.ClearTimeoutTxParams) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for ClearTimeoutTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.ClearTimeoutTxParams) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_ClearTimeoutTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearTimeoutTx'
type MockStorage_ClearTimeoutTx_Call struct {
	*mock.Call
}

// ClearTimeoutTx is a helper method to define mock.On call
//   - ctx context.Context
//   - args db.ClearTimeoutTxParams
func (_e *MockStorage_Expecter) ClearTimeoutTx(ctx interface{}, args interface{}) *MockStorage_ClearTimeoutTx_Call {
	return &MockStorage_ClearTimeoutTx_Call{Call: _e.mock.On("ClearTimeoutTx", ctx, args)}
}

func (_c *MockStorage_ClearTimeoutTx_Call) Run(run func(ctx context.Context, args db.ClearTimeoutTxParams)) *MockStorage_ClearTimeoutTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.ClearTimeoutTxParams))
	})
	return _c
}

func (_c *MockStorage_ClearTimeoutTx_Call) Return(_a0 error) *MockStorage_ClearTimeoutTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_ClearTimeoutTx_Call) RunAndReturn(run func(context.Context, db.ClearTimeoutTxParams) error) *MockStorage_ClearTimeoutTx_Call {
	_c.Call.Return(run)
	return _c
}

// ExecTx provides a mock function with given fields: ctx, fn
func (_m *MockStorage) ExecTx(ctx context.Context, fn func(*db.Queries) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for ExecTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(*db.Queries) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_ExecTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecTx'
type MockStorage_ExecTx_Call struct {
	*mock.Call
}

// ExecTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(*db.Queries) error
func (_e *MockStorage_Expecter) ExecTx(ctx interface{}, fn interface{}) *MockStorage_ExecTx_Call {
	return &MockStorage_ExecTx_Call{Call: _e.mock.On("ExecTx", ctx, fn)}
}

func (_c *MockStorage_ExecTx_Call) Run(run func(ctx context.Context, fn func(*db.Queries) error)) *MockStorage_ExecTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(*db.Queries) error))
	})
	return _c
}

func (_c *MockStorage_ExecTx_Call) Return(_a0 error) *MockStorage_ExecTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_ExecTx_Call) RunAndReturn(run func(context.Context, func(*db.Queries) error) error) *MockStorage_ExecTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferAckTx provides a mock function with given fields: ctx, arg
func (_m *MockStorage) UpdateTransferAckTx(ctx context.Context, arg db.UpdateTransferAckTxParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferAckTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferAckTxParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateTransferAckTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferAckTx'
type MockStorage_UpdateTransferAckTx_Call struct {
	*mock.Call
}

// UpdateTransferAckTx is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferAckTxParams
func (_e *MockStorage_Expecter) UpdateTransferAckTx(ctx interface{}, arg interface{}) *MockStorage_UpdateTransferAckTx_Call {
	return &MockStorage_UpdateTransferAckTx_Call{Call: _e.mock.On("UpdateTransferAckTx", ctx, arg)}
}

func (_c *MockStorage_UpdateTransferAckTx_Call) Run(run func(ctx context.Context, arg db.UpdateTransferAckTxParams)) *MockStorage_UpdateTransferAckTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferAckTxParams))
	})
	return _c
}

func (_c *MockStorage_UpdateTransferAckTx_Call) Return(_a0 error) *MockStorage_UpdateTransferAckTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateTransferAckTx_Call) RunAndReturn(run func(context.Context, db.UpdateTransferAckTxParams) error) *MockStorage_UpdateTransferAckTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferAckTxGasCostUSD provides a mock function with given fields: ctx, arg
func (_m *MockStorage) UpdateTransferAckTxGasCostUSD(ctx context.Context, arg db.UpdateTransferAckTxGasCostUSDParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferAckTxGasCostUSD")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferAckTxGasCostUSDParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateTransferAckTxGasCostUSD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferAckTxGasCostUSD'
type MockStorage_UpdateTransferAckTxGasCostUSD_Call struct {
	*mock.Call
}

// UpdateTransferAckTxGasCostUSD is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferAckTxGasCostUSDParams
func (_e *MockStorage_Expecter) UpdateTransferAckTxGasCostUSD(ctx interface{}, arg interface{}) *MockStorage_UpdateTransferAckTxGasCostUSD_Call {
	return &MockStorage_UpdateTransferAckTxGasCostUSD_Call{Call: _e.mock.On("UpdateTransferAckTxGasCostUSD", ctx, arg)}
}

func (_c *MockStorage_UpdateTransferAckTxGasCostUSD_Call) Run(run func(ctx context.Context, arg db.UpdateTransferAckTxGasCostUSDParams)) *MockStorage_UpdateTransferAckTxGasCostUSD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferAckTxGasCostUSDParams))
	})
	return _c
}

func (_c *MockStorage_UpdateTransferAckTxGasCostUSD_Call) Return(_a0 error) *MockStorage_UpdateTransferAckTxGasCostUSD_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateTransferAckTxGasCostUSD_Call) RunAndReturn(run func(context.Context, db.UpdateTransferAckTxGasCostUSDParams) error) *MockStorage_UpdateTransferAckTxGasCostUSD_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferRecvTx provides a mock function with given fields: ctx, arg
func (_m *MockStorage) UpdateTransferRecvTx(ctx context.Context, arg db.UpdateTransferRecvTxParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferRecvTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferRecvTxParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateTransferRecvTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferRecvTx'
type MockStorage_UpdateTransferRecvTx_Call struct {
	*mock.Call
}

// UpdateTransferRecvTx is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferRecvTxParams
func (_e *MockStorage_Expecter) UpdateTransferRecvTx(ctx interface{}, arg interface{}) *MockStorage_UpdateTransferRecvTx_Call {
	return &MockStorage_UpdateTransferRecvTx_Call{Call: _e.mock.On("UpdateTransferRecvTx", ctx, arg)}
}

func (_c *MockStorage_UpdateTransferRecvTx_Call) Run(run func(ctx context.Context, arg db.UpdateTransferRecvTxParams)) *MockStorage_UpdateTransferRecvTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferRecvTxParams))
	})
	return _c
}

func (_c *MockStorage_UpdateTransferRecvTx_Call) Return(_a0 error) *MockStorage_UpdateTransferRecvTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateTransferRecvTx_Call) RunAndReturn(run func(context.Context, db.UpdateTransferRecvTxParams) error) *MockStorage_UpdateTransferRecvTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferRecvTxGasCostUSD provides a mock function with given fields: ctx, arg
func (_m *MockStorage) UpdateTransferRecvTxGasCostUSD(ctx context.Context, arg db.UpdateTransferRecvTxGasCostUSDParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferRecvTxGasCostUSD")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferRecvTxGasCostUSDParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateTransferRecvTxGasCostUSD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferRecvTxGasCostUSD'
type MockStorage_UpdateTransferRecvTxGasCostUSD_Call struct {
	*mock.Call
}

// UpdateTransferRecvTxGasCostUSD is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferRecvTxGasCostUSDParams
func (_e *MockStorage_Expecter) UpdateTransferRecvTxGasCostUSD(ctx interface{}, arg interface{}) *MockStorage_UpdateTransferRecvTxGasCostUSD_Call {
	return &MockStorage_UpdateTransferRecvTxGasCostUSD_Call{Call: _e.mock.On("UpdateTransferRecvTxGasCostUSD", ctx, arg)}
}

func (_c *MockStorage_UpdateTransferRecvTxGasCostUSD_Call) Run(run func(ctx context.Context, arg db.UpdateTransferRecvTxGasCostUSDParams)) *MockStorage_UpdateTransferRecvTxGasCostUSD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferRecvTxGasCostUSDParams))
	})
	return _c
}

func (_c *MockStorage_UpdateTransferRecvTxGasCostUSD_Call) Return(_a0 error) *MockStorage_UpdateTransferRecvTxGasCostUSD_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateTransferRecvTxGasCostUSD_Call) RunAndReturn(run func(context.Context, db.UpdateTransferRecvTxGasCostUSDParams) error) *MockStorage_UpdateTransferRecvTxGasCostUSD_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferSourceTxFinalizedTime provides a mock function with given fields: ctx, arg
func (_m *MockStorage) UpdateTransferSourceTxFinalizedTime(ctx context.Context, arg db.UpdateTransferSourceTxFinalizedTimeParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferSourceTxFinalizedTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferSourceTxFinalizedTimeParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateTransferSourceTxFinalizedTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferSourceTxFinalizedTime'
type MockStorage_UpdateTransferSourceTxFinalizedTime_Call struct {
	*mock.Call
}

// UpdateTransferSourceTxFinalizedTime is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferSourceTxFinalizedTimeParams
func (_e *MockStorage_Expecter) UpdateTransferSourceTxFinalizedTime(ctx interface{}, arg interface{}) *MockStorage_UpdateTransferSourceTxFinalizedTime_Call {
	return &MockStorage_UpdateTransferSourceTxFinalizedTime_Call{Call: _e.mock.On("UpdateTransferSourceTxFinalizedTime", ctx, arg)}
}

func (_c *MockStorage_UpdateTransferSourceTxFinalizedTime_Call) Run(run func(ctx context.Context, arg db.UpdateTransferSourceTxFinalizedTimeParams)) *MockStorage_UpdateTransferSourceTxFinalizedTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferSourceTxFinalizedTimeParams))
	})
	return _c
}

func (_c *MockStorage_UpdateTransferSourceTxFinalizedTime_Call) Return(_a0 error) *MockStorage_UpdateTransferSourceTxFinalizedTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateTransferSourceTxFinalizedTime_Call) RunAndReturn(run func(context.Context, db.UpdateTransferSourceTxFinalizedTimeParams) error) *MockStorage_UpdateTransferSourceTxFinalizedTime_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferState provides a mock function with given fields: ctx, arg
func (_m *MockStorage) UpdateTransferState(ctx context.Context, arg db.UpdateTransferStateParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferStateParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateTransferState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferState'
type MockStorage_UpdateTransferState_Call struct {
	*mock.Call
}

// UpdateTransferState is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferStateParams
func (_e *MockStorage_Expecter) UpdateTransferState(ctx interface{}, arg interface{}) *MockStorage_UpdateTransferState_Call {
	return &MockStorage_UpdateTransferState_Call{Call: _e.mock.On("UpdateTransferState", ctx, arg)}
}

func (_c *MockStorage_UpdateTransferState_Call) Run(run func(ctx context.Context, arg db.UpdateTransferStateParams)) *MockStorage_UpdateTransferState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferStateParams))
	})
	return _c
}

func (_c *MockStorage_UpdateTransferState_Call) Return(_a0 error) *MockStorage_UpdateTransferState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateTransferState_Call) RunAndReturn(run func(context.Context, db.UpdateTransferStateParams) error) *MockStorage_UpdateTransferState_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferTimeoutTx provides a mock function with given fields: ctx, arg
func (_m *MockStorage) UpdateTransferTimeoutTx(ctx context.Context, arg db.UpdateTransferTimeoutTxParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferTimeoutTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferTimeoutTxParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateTransferTimeoutTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferTimeoutTx'
type MockStorage_UpdateTransferTimeoutTx_Call struct {
	*mock.Call
}

// UpdateTransferTimeoutTx is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferTimeoutTxParams
func (_e *MockStorage_Expecter) UpdateTransferTimeoutTx(ctx interface{}, arg interface{}) *MockStorage_UpdateTransferTimeoutTx_Call {
	return &MockStorage_UpdateTransferTimeoutTx_Call{Call: _e.mock.On("UpdateTransferTimeoutTx", ctx, arg)}
}

func (_c *MockStorage_UpdateTransferTimeoutTx_Call) Run(run func(ctx context.Context, arg db.UpdateTransferTimeoutTxParams)) *MockStorage_UpdateTransferTimeoutTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferTimeoutTxParams))
	})
	return _c
}

func (_c *MockStorage_UpdateTransferTimeoutTx_Call) Return(_a0 error) *MockStorage_UpdateTransferTimeoutTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateTransferTimeoutTx_Call) RunAndReturn(run func(context.Context, db.UpdateTransferTimeoutTxParams) error) *MockStorage_UpdateTransferTimeoutTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferTimeoutTxGasCostUSD provides a mock function with given fields: ctx, arg
func (_m *MockStorage) UpdateTransferTimeoutTxGasCostUSD(ctx context.Context, arg db.UpdateTransferTimeoutTxGasCostUSDParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferTimeoutTxGasCostUSD")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferTimeoutTxGasCostUSDParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateTransferTimeoutTxGasCostUSD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferTimeoutTxGasCostUSD'
type MockStorage_UpdateTransferTimeoutTxGasCostUSD_Call struct {
	*mock.Call
}

// UpdateTransferTimeoutTxGasCostUSD is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferTimeoutTxGasCostUSDParams
func (_e *MockStorage_Expecter) UpdateTransferTimeoutTxGasCostUSD(ctx interface{}, arg interface{}) *MockStorage_UpdateTransferTimeoutTxGasCostUSD_Call {
	return &MockStorage_UpdateTransferTimeoutTxGasCostUSD_Call{Call: _e.mock.On("UpdateTransferTimeoutTxGasCostUSD", ctx, arg)}
}

func (_c *MockStorage_UpdateTransferTimeoutTxGasCostUSD_Call) Run(run func(ctx context.Context, arg db.UpdateTransferTimeoutTxGasCostUSDParams)) *MockStorage_UpdateTransferTimeoutTxGasCostUSD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferTimeoutTxGasCostUSDParams))
	})
	return _c
}

func (_c *MockStorage_UpdateTransferTimeoutTxGasCostUSD_Call) Return(_a0 error) *MockStorage_UpdateTransferTimeoutTxGasCostUSD_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateTransferTimeoutTxGasCostUSD_Call) RunAndReturn(run func(context.Context, db.UpdateTransferTimeoutTxGasCostUSDParams) error) *MockStorage_UpdateTransferTimeoutTxGasCostUSD_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferWriteAckTx provides a mock function with given fields: ctx, arg
func (_m *MockStorage) UpdateTransferWriteAckTx(ctx context.Context, arg db.UpdateTransferWriteAckTxParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferWriteAckTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferWriteAckTxParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateTransferWriteAckTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferWriteAckTx'
type MockStorage_UpdateTransferWriteAckTx_Call struct {
	*mock.Call
}

// UpdateTransferWriteAckTx is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferWriteAckTxParams
func (_e *MockStorage_Expecter) UpdateTransferWriteAckTx(ctx interface{}, arg interface{}) *MockStorage_UpdateTransferWriteAckTx_Call {
	return &MockStorage_UpdateTransferWriteAckTx_Call{Call: _e.mock.On("UpdateTransferWriteAckTx", ctx, arg)}
}

func (_c *MockStorage_UpdateTransferWriteAckTx_Call) Run(run func(ctx context.Context, arg db.UpdateTransferWriteAckTxParams)) *MockStorage_UpdateTransferWriteAckTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferWriteAckTxParams))
	})
	return _c
}

func (_c *MockStorage_UpdateTransferWriteAckTx_Call) Return(_a0 error) *MockStorage_UpdateTransferWriteAckTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateTransferWriteAckTx_Call) RunAndReturn(run func(context.Context, db.UpdateTransferWriteAckTxParams) error) *MockStorage_UpdateTransferWriteAckTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferWriteAckTxFinalizedTime provides a mock function with given fields: ctx, arg
func (_m *MockStorage) UpdateTransferWriteAckTxFinalizedTime(ctx context.Context, arg db.UpdateTransferWriteAckTxFinalizedTimeParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferWriteAckTxFinalizedTime")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferWriteAckTxFinalizedTimeParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_UpdateTransferWriteAckTxFinalizedTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferWriteAckTxFinalizedTime'
type MockStorage_UpdateTransferWriteAckTxFinalizedTime_Call struct {
	*mock.Call
}

// UpdateTransferWriteAckTxFinalizedTime is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferWriteAckTxFinalizedTimeParams
func (_e *MockStorage_Expecter) UpdateTransferWriteAckTxFinalizedTime(ctx interface{}, arg interface{}) *MockStorage_UpdateTransferWriteAckTxFinalizedTime_Call {
	return &MockStorage_UpdateTransferWriteAckTxFinalizedTime_Call{Call: _e.mock.On("UpdateTransferWriteAckTxFinalizedTime", ctx, arg)}
}

func (_c *MockStorage_UpdateTransferWriteAckTxFinalizedTime_Call) Run(run func(ctx context.Context, arg db.UpdateTransferWriteAckTxFinalizedTimeParams)) *MockStorage_UpdateTransferWriteAckTxFinalizedTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferWriteAckTxFinalizedTimeParams))
	})
	return _c
}

func (_c *MockStorage_UpdateTransferWriteAckTxFinalizedTime_Call) Return(_a0 error) *MockStorage_UpdateTransferWriteAckTxFinalizedTime_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_UpdateTransferWriteAckTxFinalizedTime_Call) RunAndReturn(run func(context.Context, db.UpdateTransferWriteAckTxFinalizedTimeParams) error) *MockStorage_UpdateTransferWriteAckTxFinalizedTime_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
