// Code generated by mockery. DO NOT EDIT.

package ibcv2

import (
	context "context"

	db "github.com/cosmos/ibc-relayer/db/gen/db"

	mock "github.com/stretchr/testify/mock"
)

// MockTransferStateStorage is an autogenerated mock type for the TransferStateStorage type
type MockTransferStateStorage struct {
	mock.Mock
}

type MockTransferStateStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransferStateStorage) EXPECT() *MockTransferStateStorage_Expecter {
	return &MockTransferStateStorage_Expecter{mock: &_m.Mock}
}

// UpdateTransferState provides a mock function with given fields: ctx, arg
func (_m *MockTransferStateStorage) UpdateTransferState(ctx context.Context, arg db.UpdateTransferStateParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferStateParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransferStateStorage_UpdateTransferState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferState'
type MockTransferStateStorage_UpdateTransferState_Call struct {
	*mock.Call
}

// UpdateTransferState is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferStateParams
func (_e *MockTransferStateStorage_Expecter) UpdateTransferState(ctx interface{}, arg interface{}) *MockTransferStateStorage_UpdateTransferState_Call {
	return &MockTransferStateStorage_UpdateTransferState_Call{Call: _e.mock.On("UpdateTransferState", ctx, arg)}
}

func (_c *MockTransferStateStorage_UpdateTransferState_Call) Run(run func(ctx context.Context, arg db.UpdateTransferStateParams)) *MockTransferStateStorage_UpdateTransferState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferStateParams))
	})
	return _c
}

func (_c *MockTransferStateStorage_UpdateTransferState_Call) Return(_a0 error) *MockTransferStateStorage_UpdateTransferState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransferStateStorage_UpdateTransferState_Call) RunAndReturn(run func(context.Context, db.UpdateTransferStateParams) error) *MockTransferStateStorage_UpdateTransferState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransferStateStorage creates a new instance of MockTransferStateStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransferStateStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransferStateStorage {
	mock := &MockTransferStateStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
