// Code generated by mockery. DO NOT EDIT.

package ibcv2

import (
	context "context"

	db "github.com/cosmos/platform-relayer/db/gen/db"
	ibcv2 "github.com/cosmos/platform-relayer/relayer/ibcv2"

	mock "github.com/stretchr/testify/mock"
)

// MockIBCV2Processor is an autogenerated mock type for the IBCV2Processor type
type MockIBCV2Processor struct {
	mock.Mock
}

type MockIBCV2Processor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIBCV2Processor) EXPECT() *MockIBCV2Processor_Expecter {
	return &MockIBCV2Processor_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: i, err
func (_m *MockIBCV2Processor) Cancel(i *ibcv2.IBCV2Transfer, err error) {
	_m.Called(i, err)
}

// MockIBCV2Processor_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockIBCV2Processor_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - i *ibcv2.IBCV2Transfer
//   - err error
func (_e *MockIBCV2Processor_Expecter) Cancel(i interface{}, err interface{}) *MockIBCV2Processor_Cancel_Call {
	return &MockIBCV2Processor_Cancel_Call{Call: _e.mock.On("Cancel", i, err)}
}

func (_c *MockIBCV2Processor_Cancel_Call) Run(run func(i *ibcv2.IBCV2Transfer, err error)) *MockIBCV2Processor_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ibcv2.IBCV2Transfer), args[1].(error))
	})
	return _c
}

func (_c *MockIBCV2Processor_Cancel_Call) Return() *MockIBCV2Processor_Cancel_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIBCV2Processor_Cancel_Call) RunAndReturn(run func(*ibcv2.IBCV2Transfer, error)) *MockIBCV2Processor_Cancel_Call {
	_c.Run(run)
	return _c
}

// Process provides a mock function with given fields: ctx, i
func (_m *MockIBCV2Processor) Process(ctx context.Context, i *ibcv2.IBCV2Transfer) (*ibcv2.IBCV2Transfer, error) {
	ret := _m.Called(ctx, i)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 *ibcv2.IBCV2Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ibcv2.IBCV2Transfer) (*ibcv2.IBCV2Transfer, error)); ok {
		return rf(ctx, i)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ibcv2.IBCV2Transfer) *ibcv2.IBCV2Transfer); ok {
		r0 = rf(ctx, i)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ibcv2.IBCV2Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ibcv2.IBCV2Transfer) error); ok {
		r1 = rf(ctx, i)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIBCV2Processor_Process_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Process'
type MockIBCV2Processor_Process_Call struct {
	*mock.Call
}

// Process is a helper method to define mock.On call
//   - ctx context.Context
//   - i *ibcv2.IBCV2Transfer
func (_e *MockIBCV2Processor_Expecter) Process(ctx interface{}, i interface{}) *MockIBCV2Processor_Process_Call {
	return &MockIBCV2Processor_Process_Call{Call: _e.mock.On("Process", ctx, i)}
}

func (_c *MockIBCV2Processor_Process_Call) Run(run func(ctx context.Context, i *ibcv2.IBCV2Transfer)) *MockIBCV2Processor_Process_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ibcv2.IBCV2Transfer))
	})
	return _c
}

func (_c *MockIBCV2Processor_Process_Call) Return(_a0 *ibcv2.IBCV2Transfer, _a1 error) *MockIBCV2Processor_Process_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIBCV2Processor_Process_Call) RunAndReturn(run func(context.Context, *ibcv2.IBCV2Transfer) (*ibcv2.IBCV2Transfer, error)) *MockIBCV2Processor_Process_Call {
	_c.Call.Return(run)
	return _c
}

// ShouldProcess provides a mock function with given fields: input
func (_m *MockIBCV2Processor) ShouldProcess(input *ibcv2.IBCV2Transfer) bool {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for ShouldProcess")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(*ibcv2.IBCV2Transfer) bool); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockIBCV2Processor_ShouldProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShouldProcess'
type MockIBCV2Processor_ShouldProcess_Call struct {
	*mock.Call
}

// ShouldProcess is a helper method to define mock.On call
//   - input *ibcv2.IBCV2Transfer
func (_e *MockIBCV2Processor_Expecter) ShouldProcess(input interface{}) *MockIBCV2Processor_ShouldProcess_Call {
	return &MockIBCV2Processor_ShouldProcess_Call{Call: _e.mock.On("ShouldProcess", input)}
}

func (_c *MockIBCV2Processor_ShouldProcess_Call) Run(run func(input *ibcv2.IBCV2Transfer)) *MockIBCV2Processor_ShouldProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*ibcv2.IBCV2Transfer))
	})
	return _c
}

func (_c *MockIBCV2Processor_ShouldProcess_Call) Return(_a0 bool) *MockIBCV2Processor_ShouldProcess_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIBCV2Processor_ShouldProcess_Call) RunAndReturn(run func(*ibcv2.IBCV2Transfer) bool) *MockIBCV2Processor_ShouldProcess_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function with no fields
func (_m *MockIBCV2Processor) State() db.Ibcv2RelayStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 db.Ibcv2RelayStatus
	if rf, ok := ret.Get(0).(func() db.Ibcv2RelayStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(db.Ibcv2RelayStatus)
	}

	return r0
}

// MockIBCV2Processor_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type MockIBCV2Processor_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *MockIBCV2Processor_Expecter) State() *MockIBCV2Processor_State_Call {
	return &MockIBCV2Processor_State_Call{Call: _e.mock.On("State")}
}

func (_c *MockIBCV2Processor_State_Call) Run(run func()) *MockIBCV2Processor_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIBCV2Processor_State_Call) Return(_a0 db.Ibcv2RelayStatus) *MockIBCV2Processor_State_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockIBCV2Processor_State_Call) RunAndReturn(run func() db.Ibcv2RelayStatus) *MockIBCV2Processor_State_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIBCV2Processor creates a new instance of MockIBCV2Processor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIBCV2Processor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIBCV2Processor {
	mock := &MockIBCV2Processor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
