// Code generated by mockery. DO NOT EDIT.

package ibcv2

import (
	context "context"

	db "github.com/cosmos/platform-relayer/db/gen/db"

	mock "github.com/stretchr/testify/mock"
)

// MockUnfinishedIBCV2TransferStorage is an autogenerated mock type for the UnfinishedIBCV2TransferStorage type
type MockUnfinishedIBCV2TransferStorage struct {
	mock.Mock
}

type MockUnfinishedIBCV2TransferStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnfinishedIBCV2TransferStorage) EXPECT() *MockUnfinishedIBCV2TransferStorage_Expecter {
	return &MockUnfinishedIBCV2TransferStorage_Expecter{mock: &_m.Mock}
}

// GetUnfinishedIBCV2Transfers provides a mock function with given fields: ctx
func (_m *MockUnfinishedIBCV2TransferStorage) GetUnfinishedIBCV2Transfers(ctx context.Context) ([]db.Ibcv2Transfer, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetUnfinishedIBCV2Transfers")
	}

	var r0 []db.Ibcv2Transfer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.Ibcv2Transfer, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.Ibcv2Transfer); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Ibcv2Transfer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUnfinishedIBCV2TransferStorage_GetUnfinishedIBCV2Transfers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnfinishedIBCV2Transfers'
type MockUnfinishedIBCV2TransferStorage_GetUnfinishedIBCV2Transfers_Call struct {
	*mock.Call
}

// GetUnfinishedIBCV2Transfers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnfinishedIBCV2TransferStorage_Expecter) GetUnfinishedIBCV2Transfers(ctx interface{}) *MockUnfinishedIBCV2TransferStorage_GetUnfinishedIBCV2Transfers_Call {
	return &MockUnfinishedIBCV2TransferStorage_GetUnfinishedIBCV2Transfers_Call{Call: _e.mock.On("GetUnfinishedIBCV2Transfers", ctx)}
}

func (_c *MockUnfinishedIBCV2TransferStorage_GetUnfinishedIBCV2Transfers_Call) Run(run func(ctx context.Context)) *MockUnfinishedIBCV2TransferStorage_GetUnfinishedIBCV2Transfers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockUnfinishedIBCV2TransferStorage_GetUnfinishedIBCV2Transfers_Call) Return(_a0 []db.Ibcv2Transfer, _a1 error) *MockUnfinishedIBCV2TransferStorage_GetUnfinishedIBCV2Transfers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUnfinishedIBCV2TransferStorage_GetUnfinishedIBCV2Transfers_Call) RunAndReturn(run func(context.Context) ([]db.Ibcv2Transfer, error)) *MockUnfinishedIBCV2TransferStorage_GetUnfinishedIBCV2Transfers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTransferState provides a mock function with given fields: ctx, arg
func (_m *MockUnfinishedIBCV2TransferStorage) UpdateTransferState(ctx context.Context, arg db.UpdateTransferStateParams) error {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTransferState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateTransferStateParams) error); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUnfinishedIBCV2TransferStorage_UpdateTransferState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTransferState'
type MockUnfinishedIBCV2TransferStorage_UpdateTransferState_Call struct {
	*mock.Call
}

// UpdateTransferState is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateTransferStateParams
func (_e *MockUnfinishedIBCV2TransferStorage_Expecter) UpdateTransferState(ctx interface{}, arg interface{}) *MockUnfinishedIBCV2TransferStorage_UpdateTransferState_Call {
	return &MockUnfinishedIBCV2TransferStorage_UpdateTransferState_Call{Call: _e.mock.On("UpdateTransferState", ctx, arg)}
}

func (_c *MockUnfinishedIBCV2TransferStorage_UpdateTransferState_Call) Run(run func(ctx context.Context, arg db.UpdateTransferStateParams)) *MockUnfinishedIBCV2TransferStorage_UpdateTransferState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateTransferStateParams))
	})
	return _c
}

func (_c *MockUnfinishedIBCV2TransferStorage_UpdateTransferState_Call) Return(_a0 error) *MockUnfinishedIBCV2TransferStorage_UpdateTransferState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUnfinishedIBCV2TransferStorage_UpdateTransferState_Call) RunAndReturn(run func(context.Context, db.UpdateTransferStateParams) error) *MockUnfinishedIBCV2TransferStorage_UpdateTransferState_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnfinishedIBCV2TransferStorage creates a new instance of MockUnfinishedIBCV2TransferStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnfinishedIBCV2TransferStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnfinishedIBCV2TransferStorage {
	mock := &MockUnfinishedIBCV2TransferStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
